{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.4.aar",
          "url": "bgeo-android-0.13.4.aar",
          "size": 323774,
          "sha512": "97b7c570a2d228e88af5fd0a4c49002e0c5a05150fc077c5e188a2a300c25e421f3ba95f5cdb1e08b23fd357d358187350148925fdbf64887c35a1c85313f374",
          "sha256": "b397853791ea92b4758c797946c0b43cb1c478c6df34436fecec88db70efe04c",
          "sha1": "3477c0dfaacf512eb010992b5ddde44046f259bb",
          "md5": "3fc0c6a1263f84c5304aac311ffc01f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.4.aar",
          "url": "bgeo-android-0.13.4.aar",
          "size": 323774,
          "sha512": "97b7c570a2d228e88af5fd0a4c49002e0c5a05150fc077c5e188a2a300c25e421f3ba95f5cdb1e08b23fd357d358187350148925fdbf64887c35a1c85313f374",
          "sha256": "b397853791ea92b4758c797946c0b43cb1c478c6df34436fecec88db70efe04c",
          "sha1": "3477c0dfaacf512eb010992b5ddde44046f259bb",
          "md5": "3fc0c6a1263f84c5304aac311ffc01f1"
        }
      ]
    }
  ]
}
