{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.2.aar",
          "url": "bgeo-android-0.13.2.aar",
          "size": 319692,
          "sha512": "9fc84396f256224effd3c54812312aa3448d57e350be38f7f675787c6832feba0703193035c0c6b6a440e893856eb3fdbf62507b30414fee60e55070555d855d",
          "sha256": "17c88f88f6d045f9631c3700c885f33eef0de8c1e26d468dc05fdd3e2c44371e",
          "sha1": "dc7965308642cbf09050f896d12a9536e2f849e9",
          "md5": "ea89784c132761efdb31cdbd110c0bda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.2.aar",
          "url": "bgeo-android-0.13.2.aar",
          "size": 319692,
          "sha512": "9fc84396f256224effd3c54812312aa3448d57e350be38f7f675787c6832feba0703193035c0c6b6a440e893856eb3fdbf62507b30414fee60e55070555d855d",
          "sha256": "17c88f88f6d045f9631c3700c885f33eef0de8c1e26d468dc05fdd3e2c44371e",
          "sha1": "dc7965308642cbf09050f896d12a9536e2f849e9",
          "md5": "ea89784c132761efdb31cdbd110c0bda"
        }
      ]
    }
  ]
}
