{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.3.aar",
          "url": "bgeo-android-0.13.3.aar",
          "size": 319990,
          "sha512": "08b8a2499f3a3e2d65fb6517c256931bf67eb91e8d2654be122f161c3b81f7ccb46cd3d87854f9f2701b4d9ab60282e65a98cfacefd3199ec57aa3448f546c51",
          "sha256": "35f9b74683c0985771d155cd09b5a96b22814179978462a7c965927af91d88cf",
          "sha1": "e5720a29e701211f1edd92669109eb5b3c0f2d7e",
          "md5": "eb94ffa32bf09d4673de86a6867b33a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.3.aar",
          "url": "bgeo-android-0.13.3.aar",
          "size": 319990,
          "sha512": "08b8a2499f3a3e2d65fb6517c256931bf67eb91e8d2654be122f161c3b81f7ccb46cd3d87854f9f2701b4d9ab60282e65a98cfacefd3199ec57aa3448f546c51",
          "sha256": "35f9b74683c0985771d155cd09b5a96b22814179978462a7c965927af91d88cf",
          "sha1": "e5720a29e701211f1edd92669109eb5b3c0f2d7e",
          "md5": "eb94ffa32bf09d4673de86a6867b33a0"
        }
      ]
    }
  ]
}
