{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bgeo",
    "module": "bgeo-android",
    "version": "0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.12.1.aar",
          "url": "bgeo-android-0.12.1.aar",
          "size": 317678,
          "sha512": "975fabaeba6bd75ff9c8c3b4ff4eb23ade53d1c24ce7c850a5207d9690c8ece8b7bd12f11515a14f4ff1d9417977d70d292c0cc5438d385cb671159debcaf8c2",
          "sha256": "f70025e3ee93567a92339f577b953cf9d400a80f0f97d5ba381d818cb77368f1",
          "sha1": "765d7df525398c3d301a6bd00a50d6efc86699e0",
          "md5": "1128823a8243ba910d1ce91fa72de1fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.12.1.aar",
          "url": "bgeo-android-0.12.1.aar",
          "size": 317678,
          "sha512": "975fabaeba6bd75ff9c8c3b4ff4eb23ade53d1c24ce7c850a5207d9690c8ece8b7bd12f11515a14f4ff1d9417977d70d292c0cc5438d385cb671159debcaf8c2",
          "sha256": "f70025e3ee93567a92339f577b953cf9d400a80f0f97d5ba381d818cb77368f1",
          "sha1": "765d7df525398c3d301a6bd00a50d6efc86699e0",
          "md5": "1128823a8243ba910d1ce91fa72de1fc"
        }
      ]
    }
  ]
}
