{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.1.aar",
          "url": "bgeo-android-0.13.1.aar",
          "size": 318081,
          "sha512": "491ea8b5f0777b5405f6dc77f15fc25f91dcd7c2346eb984e7fa38d3123dd5d171346fc916bf29a4ccef1262bf2ffd803b87ba8360800a37aaa017b080ed7553",
          "sha256": "fa4a9904346ab11ad07262ef86a6808d639f5cb0d36dec9b00b16581ef50de9f",
          "sha1": "8b8a5e40a2b4e391ea7bb48be4315e30f872ad7d",
          "md5": "9d0708eddf6b001207551e48955d8b7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.1.aar",
          "url": "bgeo-android-0.13.1.aar",
          "size": 318081,
          "sha512": "491ea8b5f0777b5405f6dc77f15fc25f91dcd7c2346eb984e7fa38d3123dd5d171346fc916bf29a4ccef1262bf2ffd803b87ba8360800a37aaa017b080ed7553",
          "sha256": "fa4a9904346ab11ad07262ef86a6808d639f5cb0d36dec9b00b16581ef50de9f",
          "sha1": "8b8a5e40a2b4e391ea7bb48be4315e30f872ad7d",
          "md5": "9d0708eddf6b001207551e48955d8b7b"
        }
      ]
    }
  ]
}
