{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bgeo",
    "module": "bgeo-android",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.12.0.aar",
          "url": "bgeo-android-0.12.0.aar",
          "size": 317596,
          "sha512": "a652c5f5493ee22cb090de3ecc3b127e16d81838c6081d004cbcee8225d9fab1f738a8f6ad8f08bb4138df795dc0644871fb3726f1a8c94dd0ce3ae6599623c7",
          "sha256": "30752d95a38874f3590f26e2ede738291a3acc2b69ce0d1e54a42b85064b1c8e",
          "sha1": "bcdca8eb63c39c74ff16d832b5f9388b1e67a086",
          "md5": "355df1186209c814959efe4a760b5954"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.12.0.aar",
          "url": "bgeo-android-0.12.0.aar",
          "size": 317596,
          "sha512": "a652c5f5493ee22cb090de3ecc3b127e16d81838c6081d004cbcee8225d9fab1f738a8f6ad8f08bb4138df795dc0644871fb3726f1a8c94dd0ce3ae6599623c7",
          "sha256": "30752d95a38874f3590f26e2ede738291a3acc2b69ce0d1e54a42b85064b1c8e",
          "sha1": "bcdca8eb63c39c74ff16d832b5f9388b1e67a086",
          "md5": "355df1186209c814959efe4a760b5954"
        }
      ]
    }
  ]
}
