{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.13.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.5.aar",
          "url": "bgeo-android-0.13.5.aar",
          "size": 323764,
          "sha512": "0b1712937c9b962a0cf125fc4b77f560d53ab029bf9f2ed08e2590607ff141a95def6ec25ed0a7868659d9ff209a75b41b9c503c962e0bb6578a86381a493210",
          "sha256": "5b66df80ca99e7ecf4b1f4b1189b9c989e4392701a101c5bf0b3b0ba622abc66",
          "sha1": "b43fc6a59802b9bdef65a9c530c711e39f3ea98a",
          "md5": "3b29c7fdd8d3da0acbe9f379c70ae2c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.13.5.aar",
          "url": "bgeo-android-0.13.5.aar",
          "size": 323764,
          "sha512": "0b1712937c9b962a0cf125fc4b77f560d53ab029bf9f2ed08e2590607ff141a95def6ec25ed0a7868659d9ff209a75b41b9c503c962e0bb6578a86381a493210",
          "sha256": "5b66df80ca99e7ecf4b1f4b1189b9c989e4392701a101c5bf0b3b0ba622abc66",
          "sha1": "b43fc6a59802b9bdef65a9c530c711e39f3ea98a",
          "md5": "3b29c7fdd8d3da0acbe9f379c70ae2c9"
        }
      ]
    }
  ]
}
